In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
#0 - cat, 1- dog, 2-tiger
actuals = torch.tensor([0,2,1])
predictions = torch.tensor([[-2.5,-3.4,-5.5],[-2.6,-5.5,5.1],[-5.1,4.2,1.8]],dtype=torch.float)

In [ ]:
torch.exp(predictions) / torch.exp(predictions).sum(dim=1,keepdim=True)

tensor([[6.8664e-01, 2.7917e-01, 3.4186e-02],
        [4.5261e-04, 2.4904e-05, 9.9952e-01],
        [8.3813e-05, 9.1675e-01, 8.3166e-02]])

In [ ]:
prediction_softmax = torch.exp(predictions) / torch.exp(predictions).sum(dim=1,keepdim=True)
prediction_softmax

tensor([[9.9069e-01, 3.0071e-04, 9.0106e-03],
        [4.5261e-04, 2.4904e-05, 9.9952e-01],
        [8.3813e-05, 9.1675e-01, 8.3166e-02]])

In [ ]:
torch.softmax(predictions, dim=1)

tensor([[9.9069e-01, 3.0071e-04, 9.0106e-03],
        [4.5261e-04, 2.4904e-05, 9.9952e-01],
        [8.3813e-05, 9.1675e-01, 8.3166e-02]])

In [ ]:
-torch.log(prediction_softmax[[0,1,2],actuals])

tensor([0.0094, 0.0005, 0.0869])

In [ ]:
-torch.log(prediction_softmax[[0,1,2],actuals]).mean()

tensor(0.0323)

In [ ]:
F.cross_entropy(predictions, actuals)

tensor(0.0323)

In [ ]:
F.cross_entropy??

In [ ]:
torch.exp(torch.tensor([9,6,3], dtype=torch.float))

tensor([8103.0840,  403.4288,   20.0855])

In [ ]:
F.log_softmax(predictions,dim=1)

tensor([[-9.3549e-03, -8.1094e+00, -4.7094e+00],
        [-7.7005e+00, -1.0600e+01, -4.7768e-04],
        [-9.3869e+00, -8.6920e-02, -2.4869e+00]])

In [ ]:
F.nll_loss(F.log_softmax(predictions,dim=1),actuals)

tensor(0.0323)

Binary Cross Entropy, Multilabel classification problems

In [ ]:
actuals = torch.tensor([[0,1,1],[1,1,0],[0,0,1]],dtype=torch.float)
predictions = torch.tensor([[-2.,-8.,-5.3],[4.4,5.5,-2.],[-4.,-3.3,5.]],dtype=torch.float)

In [ ]:
1/ (1+ torch.exp(-predictions))

tensor([[1.1920e-01, 3.3535e-04, 4.9668e-03],
        [9.8787e-01, 9.9593e-01, 1.1920e-01],
        [1.7986e-02, 3.5571e-02, 9.9331e-01]])

In [ ]:
prediction_sigmoid = torch.sigmoid(predictions)
prediction_sigmoid

tensor([[0.8808, 0.9997, 0.9950],
        [0.9879, 0.9959, 0.1192],
        [0.0180, 0.0356, 0.9933]])

In [ ]:
-torch.log(torch.where(actuals==1, prediction_sigmoid, 1-prediction_sigmoid)).mean()

tensor(0.2596)

In [ ]:
F.binary_cross_entropy_with_logits(predictions, actuals)

tensor(0.2596)

In [ ]:
-torch.log(torch.tensor(0.12))

tensor(2.1203)

In [ ]:
actuals = torch.tensor([10.,20.,5.,3.],dtype=torch.float)
predictions = torch.tensor([8,18,2,1],dtype=torch.float)

worst_predictions = torch.tensor([500,-200,130,6])
avg_predictions = torch.tensor([9.5,9.5,9.5,9.5])

In [ ]:
((actuals-avg_predictions)**2).sum()

tensor(173.)

In [ ]:
((actuals - 9.5)**2).sum()

tensor(173.)

In [ ]:
1 - 173/173

0.0