In [ ]:
!nvidia-smi

Tue Nov 10 07:43:27 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    23W / 300W |      0MiB / 16130MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Cross Entropy Loss function

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
actuals = torch.tensor([0,2,1])
predictions = torch.tensor([[2.3,-5.,-2.8],[0.9,1.1,1.9],[-2.2,2.6,-12.2]],dtype=torch.float)

In [ ]:
prediction_softmax = torch.exp(predictions)/torch.exp(predictions).sum(dim=1,keepdim=True)
prediction_softmax

tensor([[9.9327e-01, 6.7099e-04, 6.0557e-03],
        [2.0244e-01, 2.4726e-01, 5.5029e-01],
        [8.1626e-03, 9.9184e-01, 3.7058e-07]])

In [ ]:
prediction_softmax[[0,1,2],actuals]

tensor([0.9933, 0.5503, 0.9918])

In [ ]:
-torch.log(prediction_softmax[[0,1,2],actuals])

tensor([0.0067, 0.5973, 0.0082])

In [ ]:
-torch.log(prediction_softmax[[0,1,2],actuals]).mean()

tensor(0.2041)

In [ ]:
#Cross Entropy = Log Softmax + NLLLoss

In [ ]:
actuals

tensor([0, 2, 1])

In [ ]:
F.log_softmax(predictions,dim=1)

tensor([[-6.7495e-03, -7.3067e+00, -5.1067e+00],
        [-1.5973e+00, -1.3973e+00, -5.9730e-01],
        [-4.8082e+00, -8.1964e-03, -1.4808e+01]])

In [ ]:
F.nll_loss(F.log_softmax(predictions,dim=1),actuals)

tensor(0.2041)

In [ ]:
F.cross_entropy(predictions,actuals)

tensor(0.2041)

In [ ]:
F.cross_entropy??

In [ ]:
actuals = torch.tensor([[1,1,0],[1,0,1],[0,0,1]],dtype=torch.float)
predictions = torch.tensor([[3.6,1.9,-2.2],[1.2,-2.9,1.9],[-2.3,-0.4,0.9]],dtype=torch.float)

In [ ]:
torch.sigmoid(torch.tensor(-3.9))

tensor(0.0198)

In [ ]:
torch.exp(torch.tensor([2.5,2.8,2.9])) / torch.exp(torch.tensor([2.5,2.8,2.9])).sum()

tensor([0.2603, 0.3514, 0.3883])

In [ ]:
torch.sigmoid(torch.tensor([2.5,2.8,2.9]))

tensor([0.9241, 0.9427, 0.9478])

$$\sigma (z)= \frac {1} {1+e ^{-z}}$$

In [ ]:
actuals = torch.tensor([[1,1,0],[1,0,1],[0,0,1]],dtype=torch.float)
predictions = torch.tensor([[3.6,1.9,-2.2],[1.2,-2.9,1.9],[-2.3,-0.4,0.9]],dtype=torch.float)

In [ ]:
prediction_sigmoid = torch.sigmoid(predictions)
prediction_sigmoid

tensor([[0.9734, 0.8699, 0.0998],
        [0.7685, 0.0522, 0.8699],
        [0.0911, 0.4013, 0.7109]])

In [ ]:
torch.where(actuals==1, prediction_sigmoid, 1-prediction_sigmoid)

tensor([[0.9734, 0.8699, 0.9002],
        [0.7685, 0.9478, 0.8699],
        [0.9089, 0.5987, 0.7109]])

In [ ]:
-torch.log(torch.where(actuals==1, prediction_sigmoid, 1-prediction_sigmoid)).mean()

tensor(0.1864)

In [ ]:
F.binary_cross_entropy_with_logits(predictions, actuals)

tensor(0.1864)

In [ ]:
!wget --header="Host: storage.googleapis.com" --header="User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36" --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" --header="Accept-Language: en-US,en;q=0.9,id;q=0.8,ms;q=0.7,ta;q=0.6" --header="Referer: https://www.kaggle.com/" "https://storage.googleapis.com/kaggle-data-sets/1938/3914/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20201110%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20201110T083443Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=107fb4bd47df24e8c13ca4eebcbae25d5a19af7af94983f1522d74ce73481f9070b42d0a7568396029435dc8d3c13c9cbc0d681da479de3228736f99d7cb2c7b5c5483c394950b7f8b63c466af165c456baf82686200845898770deb9a307bf378fd7d6a50dea21604bed84f414ee2990bae63794b887a91703b7acdaa2174ede5fac693e6e7dedb63f74b406079db2382efac5273db66823f3c695eb268f5d9117c635e8913693101ea3a51fad7e119d4e24fe7e22d07d7be08a762406117bbebbef4a7a846772cd93506a1b4e3b2b4b138b6b654bd81d42cb8095804cb4d667dbb22465a23d422367e8245528f2e80a6796e445715cdd0de6379cdb16df17c" -c -O 'archive.zip'

--2020-11-10 08:35:07--  https://storage.googleapis.com/kaggle-data-sets/1938/3914/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20201110%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20201110T083443Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=107fb4bd47df24e8c13ca4eebcbae25d5a19af7af94983f1522d74ce73481f9070b42d0a7568396029435dc8d3c13c9cbc0d681da479de3228736f99d7cb2c7b5c5483c394950b7f8b63c466af165c456baf82686200845898770deb9a307bf378fd7d6a50dea21604bed84f414ee2990bae63794b887a91703b7acdaa2174ede5fac693e6e7dedb63f74b406079db2382efac5273db66823f3c695eb268f5d9117c635e8913693101ea3a51fad7e119d4e24fe7e22d07d7be08a762406117bbebbef4a7a846772cd93506a1b4e3b2b4b138b6b654bd81d42cb8095804cb4d667dbb22465a23d422367e8245528f2e80a6796e445715cdd0de6379cdb16df17c
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.127.128, 108.177.119.128, 108.177.126.128, ...
Connecting to storage.go

In [ ]:
!unzip archive.zip

Archive:  archive.zip
  inflating: book_tags.csv           
  inflating: books.csv               
  inflating: ratings.csv             
  inflating: sample_book.xml         
  inflating: tags.csv                
  inflating: to_read.csv             


In [ ]:
import pandas as pd

In [ ]:
ratings = pd.read_csv('ratings.csv')

In [ ]:
# !git clone https://github.com/fastai/fastai
# !pip install -e "fastai[dev]"

In [ ]:
ratings

book_id  user_id  rating
0             1      314       5
1             1      439       3
2             1      588       5
3             1     1169       4
4             1     1185       4
...         ...      ...     ...
981751    10000    48386       5
981752    10000    49007       4
981753    10000    49383       5
981754    10000    50124       5
981755    10000    51328       1

[981756 rows x 3 columns]